### ISSUE TITLE
Getting a 404 on an npm install for har-validator@5.1.2

### ISSUE THREAD

**Issue by DavisChang** [uxpin-merge/uxpin-merge-boilerplate#4]
npm ERR! 404 Not Found: har-validator@5.1.2

But this guy(cdimascio) was able to fix it, and It really helps.
https://github.com/ahmadnassri/node-har-validator/issues/113

**Comment by marcintreder** [comment]
Hey @DavisChang! Thanks for reporting! Weird problem! Deleting package-lock.json helps. I'm temporary removing it from the repo to help with integrations with Merge.
